import { assetClassBacktest, riskRegimeBacktest, scoreRangeBacktest, volRegimeBacktest } from "@/lib/demo/backtest";
import { BacktestClient } from "./BacktestClient";
import { AlertTriangle } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { requireEntitlement } from "@/lib/auth/dal";
import { isDemoOnly } from "@/services/data-mode";

export const metadata = { title: "Backtesting — Market Intelligence AI" };
export const dynamic = "force-dynamic";

// Phase 18 (public-launch demo sweep): every statistic here (win rates,
// average returns, sample sizes) is generated by a seeded RNG, not computed
// from real historical scores — this codebase's real score history
// (factor_scores / score history tables) hasn't accumulated enough depth
// yet for a genuine bucketed backtest. Demo-only; outside demo mode this
// shows an honest "not available yet" state instead of fabricated
// performance statistics.
export default async function BacktestingPage() {
  await requireEntitlement();
  if (!isDemoOnly()) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-xl font-semibold">Historical Score Testing</h1>
        </div>
        <Card>
          <p className="text-sm text-(--text-faint) py-6 text-center">
            Not available yet — a real backtest requires more accumulated real score history than currently exists. It is not shown with simulated data.
          </p>
        </Card>
      </div>
    );
  }
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">Historical Score Testing</h1>
        <p className="text-sm text-(--text-faint) mt-1">
          Forward 1-, 5- and 20-day returns following each historical score reading, bucketed by score range. Built to avoid look-ahead bias: every bucket only uses information available at the time the score was recorded.
        </p>
      </div>

      <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3 flex items-start gap-2.5">
        <AlertTriangle size={16} className="text-amber-400 mt-0.5 shrink-0" />
        <p className="text-sm text-amber-200">
          Demo mode — these figures are simulated for illustration, not computed from real trades. Past performance does not guarantee future results.
        </p>
      </div>

      <BacktestClient scoreRange={scoreRangeBacktest()} byAssetClass={assetClassBacktest()} byVolRegime={volRegimeBacktest()} byRiskRegime={riskRegimeBacktest()} />
    </div>
  );
}
