import { NewsArticle } from "../types";
import { daysAgo } from "../time";

// Curated demo newsroom. In production this feed would be produced by the
// News Intelligence pipeline (dedupe -> classify -> score) described in the
// product spec; here it's hand-seeded so every interpretation stays legible.
export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: "n1",
    headline: "Fed officials signal patience, push back on near-term rate cuts",
    source: "Wire Service",
    publishedAt: daysAgo(0.1),
    affectedMarkets: ["EURUSD", "GBPUSD", "USDJPY", "XAUUSD", "SPX500", "NAS100"],
    interpretation: "Bullish",
    importance: 88,
    urgency: 74,
    confidence: 80,
    expectedImpactDuration: "2-5 trading days",
    relatedStoryIds: ["n5"],
    explanation:
      "Hawkish-leaning commentary raises the probability the Fed holds rates higher for longer, which is broadly USD-supportive and a headwind for non-yielding assets like gold.",
    isPriced: false,
    topic: "Monetary Policy",
  },
  {
    id: "n2",
    headline: "Gold extends rally as real yields slip and dollar softens",
    source: "Markets Desk",
    publishedAt: daysAgo(0.3),
    affectedMarkets: ["XAUUSD", "XAGUSD"],
    interpretation: "Bullish",
    importance: 70,
    urgency: 55,
    confidence: 72,
    expectedImpactDuration: "1-3 trading days",
    relatedStoryIds: ["n1"],
    explanation:
      "Falling real yields lower the opportunity cost of holding non-yielding bullion; confirmed by accompanying dollar weakness in the same session.",
    isPriced: true,
    topic: "Commodities",
  },
  {
    id: "n3",
    headline: "Eurozone PMI beats expectations, services sector leads rebound",
    source: "Regional Wire",
    publishedAt: daysAgo(0.8),
    affectedMarkets: ["EURUSD", "EURGBP", "EURJPY", "DAX40"],
    interpretation: "Bullish",
    importance: 62,
    urgency: 40,
    confidence: 65,
    expectedImpactDuration: "Through next data cycle",
    relatedStoryIds: [],
    explanation:
      "A beat on the composite PMI supports the eurozone growth score and narrows the growth gap versus the US, a mild tailwind for EUR crosses.",
    isPriced: false,
    topic: "Economic Growth",
  },
  {
    id: "n4",
    headline: "Crude oil slides on surprise inventory build and demand concerns",
    source: "Energy Wire",
    publishedAt: daysAgo(0.4),
    affectedMarkets: ["WTIUSD", "NATGAS"],
    interpretation: "Bearish",
    importance: 65,
    urgency: 58,
    confidence: 68,
    expectedImpactDuration: "1-2 trading days",
    relatedStoryIds: [],
    explanation:
      "A larger-than-forecast inventory build points to softer near-term demand, pressuring the technical trend score lower.",
    isPriced: false,
    topic: "Commodities",
  },
  {
    id: "n5",
    headline: "US 10-year yield climbs to three-month high after strong jobs data",
    source: "Wire Service",
    publishedAt: daysAgo(1.1),
    affectedMarkets: ["USDJPY", "SPX500", "NAS100", "XAUUSD"],
    interpretation: "Mixed",
    importance: 74,
    urgency: 50,
    confidence: 60,
    expectedImpactDuration: "2-4 trading days",
    relatedStoryIds: ["n1"],
    explanation:
      "Higher yields support the dollar and pressure gold, but also raise borrowing-cost concerns for equities — the net equity impact is mixed pending confirmation from price action.",
    isPriced: false,
    topic: "Rates",
  },
  {
    id: "n6",
    headline: "Bank of Japan officials hint at gradual policy normalization",
    source: "Asia Desk",
    publishedAt: daysAgo(1.6),
    affectedMarkets: ["USDJPY", "EURJPY", "GBPJPY", "NIKKEI225"],
    interpretation: "Bullish",
    importance: 80,
    urgency: 62,
    confidence: 58,
    expectedImpactDuration: "Through next BOJ meeting",
    relatedStoryIds: [],
    explanation:
      "Comments open the door to further rate normalization, which would narrow the rate differential and is JPY-supportive (bearish for USD/JPY) — confidence is moderate given no formal guidance yet.",
    isPriced: false,
    topic: "Monetary Policy",
  },
  {
    id: "n7",
    headline: "Bitcoin ETF inflows accelerate for a fourth straight week",
    source: "Crypto Desk",
    publishedAt: daysAgo(0.6),
    affectedMarkets: ["BTCUSD", "ETHUSD"],
    interpretation: "Bullish",
    importance: 58,
    urgency: 35,
    confidence: 70,
    expectedImpactDuration: "1-2 weeks",
    relatedStoryIds: [],
    explanation: "Sustained institutional inflows corroborate the improving institutional-positioning score for crypto.",
    isPriced: false,
    topic: "Flows",
  },
  {
    id: "n8",
    headline: "Escalation in Middle East tensions lifts safe-haven demand",
    source: "Geopolitics Wire",
    publishedAt: daysAgo(2.2),
    affectedMarkets: ["XAUUSD", "WTIUSD", "USDCHF", "USDJPY"],
    interpretation: "Mixed",
    importance: 82,
    urgency: 85,
    confidence: 45,
    expectedImpactDuration: "Unclear — developing situation",
    relatedStoryIds: [],
    explanation:
      "Headline risk is elevated but the situation is fluid; directional impact on oil vs. safe-haven flows is not yet confirmed, so confidence is deliberately capped.",
    isPriced: false,
    topic: "Geopolitics",
  },
  {
    id: "n9",
    headline: "UK retail sales fall for second consecutive month",
    source: "Regional Wire",
    publishedAt: daysAgo(1.9),
    affectedMarkets: ["GBPUSD", "EURGBP", "GBPJPY", "FTSE100"],
    interpretation: "Bearish",
    importance: 55,
    urgency: 30,
    confidence: 63,
    expectedImpactDuration: "Through next data cycle",
    relatedStoryIds: [],
    explanation: "Weaker consumer spending drags on the UK growth score, a modest headwind for sterling.",
    isPriced: true,
    topic: "Economic Growth",
  },
  {
    id: "n10",
    headline: "Silver outperforms gold as industrial demand outlook improves",
    source: "Markets Desk",
    publishedAt: daysAgo(0.9),
    affectedMarkets: ["XAGUSD", "COPPER"],
    interpretation: "Bullish",
    importance: 48,
    urgency: 25,
    confidence: 61,
    expectedImpactDuration: "1 week",
    relatedStoryIds: [],
    explanation: "Improving manufacturing PMIs across major economies support industrial-metal demand expectations.",
    isPriced: false,
    topic: "Commodities",
  },
  {
    id: "n11",
    headline: "Analyst note: Russell 2000 breadth narrows despite index gains",
    source: "Research Note",
    publishedAt: daysAgo(3.4),
    affectedMarkets: ["RUT2000"],
    interpretation: "Unclear",
    importance: 40,
    urgency: 20,
    confidence: 38,
    expectedImpactDuration: "Unclear",
    relatedStoryIds: [],
    explanation:
      "Data quality on breadth internals is limited in this feed; direction is left unclear rather than inferring an outcome from partial data.",
    isPriced: false,
    topic: "Technical",
  },
  {
    id: "n12",
    headline: "New Zealand dollar slides after RBNZ opens door to cuts",
    source: "Asia-Pacific Desk",
    publishedAt: daysAgo(1.3),
    affectedMarkets: ["NZDUSD"],
    interpretation: "Bearish",
    importance: 66,
    urgency: 55,
    confidence: 71,
    expectedImpactDuration: "Through next RBNZ meeting",
    relatedStoryIds: [],
    explanation: "A dovish pivot lowers the interest-rate score and rate-differential outlook for the currency.",
    isPriced: false,
    topic: "Monetary Policy",
  },
];
